logLevel: 'debug'
bot:
  token: 'TOKEN'
  prefix: '!'
  owners: ['Owner ID 1', 'Owner ID 2']
database:
  host: '127.0.0.1'
  port: 5432
  user: 'modmail'
  password: '1234'
  database: 'postgres'
  schema: 'modmail'
